[project]
name = "example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "frida>=17.1.3",
    "frida-tools>=14.1.1",
]
